Feature/prog2 22 refactor
sorinlzr/fhmdb pull request #29
Opened 2023-05-09 20:18 UTC by sorinlzr

- add watchlist view
- implement logic for adding and removing movies from watchlist
- add error handling
- refactor several files

2023-05-11 17:05 UTC, burakkongo submitted a review, later dismissed
Lgtm. Good job man. Pula

2023-05-13 10:28 UTC, benniii1 requested changes
Looks good! Cool that you extracted the separate views to an abstract class and reused it and found out how to make the navigation to be an overlay :)

However, the movie-cell does not show the Remove field in the watchlist-view. I added the needed code in the comments of the review.

2023-05-13 10:28 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/fhmdb/controller/WatchlistController.java
> +        super.initialize();
### Remove Button not shown in the Movie-Cell

Add this before super.initialize():
`this.isWatchlistCell = true;`

2023-05-13 10:28 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/fhmdb/controller/AbstractViewController.java
> +
### Remove Button not shown in the Movie-Cell

Add the following code here:
`protected boolean isWatchlistCell = false;`

2023-05-13 10:28 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/fhmdb/controller/AbstractViewController.java
> +        movieListView.setCellFactory(e -> new MovieCell(onWatchlistButtonClicked));
### Remove Button not shown in the Movie-Cell

Refactor to this
`movieListView.setCellFactory(e -> new MovieCell(onWatchlistButtonClicked, isWatchlistCell));`

2023-05-13 10:28 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/fhmdb/ui/MovieCell.java
> +
### Remove Button not shown in the Movie-Cell

Add this here:
`private final boolean isWatchlistCell;`

2023-05-13 10:28 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/fhmdb/ui/MovieCell.java
> +                setGraphic(graphic);
### Remove Button not shown in the Movie-Cell

Add this before setGraphic(graphic)
`if (isWatchlistCell) controller.addToWatchlist();`

2023-05-13 10:28 UTC, benniii1 commented on src/main/java/at/ac/fhcampuswien/fhmdb/ui/MovieCell.java
> +
### Remove Button not shown in the Movie-Cell

Change to:
`public MovieCell(ClickEventHandler<Movie> clickEventHandler, boolean isWatchlistCell) {
        super();
        this.clickEventHandler = clickEventHandler;
        this.isWatchlistCell = isWatchlistCell;
    }`

2023-05-14 16:14 UTC, benniii1 approved these changes

2023-05-14 16:21 UTC, merged